Repository pirogramming/Urabi, pull requests merged in 2025-02, with the labels that each got.

#31 [chore] 프로젝트 의존성 패키지 추가
  requirements.txt
Labels: chore

#32 [Feat] base 파일 구조 일부 수정 및 url연결
  config/urls.py
  flash/urls.py
  market/views.py
  templates/base/base.html
  templates/flash/flash_list.html
  templates/login/login.html
  templates/main/main.html
  templates/main/mainbeforeLogin.html
  templates/register/register.html
  users/urls.py
  users/views.py
Labels: 🔧 refactor, 💡 feat

#40 [feat] Urabi 챗봇 구현
  accompany/migrations/0002_remove_travel_participant_travel_and_more.py
  chatbot/__init__.py
  chatbot/admin.py
  chatbot/apps.py
  chatbot/migrations/__init__.py
  chatbot/models.py
  chatbot/tests.py
  chatbot/urls.py
  chatbot/views.py
  config/settings.py
  config/urls.py
  templates/chatbot/chatbot.html
Labels: 💡 feat

#41 [chore] 프로젝트 의존성 패키지 추가
  requirements.txt
Labels: chore

#46 [fix] migration 충돌 해결
  accompany/migrations/0001_initial.py
  accompany/migrations/0002_remove_travel_participant_travel_and_more.py
  accompany/migrations/0002_rename_travel_participant_travelparticipants_and_more.py
  accompany/migrations/0003_alter_travelgroup_photo.py
Labels: 🛠️ fix

#56 [feat] 실시간 채팅 기능 구현 초안 코드 작성
  chat/consumers.py
  chat/models.py
  chat/routing.py
  chat/serializers.py
  chat/templates/chat/room_user1.html
  chat/templates/chat/room_user2.html
  chat/urls.py
  chat/views.py
  config/settings.py
Labels: 🎨 design, 💡 feat, 🛠️ fix

#57 [chore] 프로젝트 의존성 패키지 추가
  requirements.txt
Labels: chore

#69 [chore] 프로젝트 의존성 패키지 업데이트
  requirements.txt
Labels: chore

#77 [fix] accompany 마이그레이션 참조 수정
  accompany/migrations/0004_travelgroup_gender.py
Labels: bug

#80 [fix] accommodation_location.html에서 지도 새로고침 해야 로딩되는 문제 해결
  static/accommodation/accommodation_map.js
  static/accommodation/accommodation_map_list.js
  templates/accommodation/accommodation_location.html
Labels: 🛠️ fix

#81 [refactor] accommodation_location.html에서 숙소 리스트에 호텔 로드뷰 추가
  static/accommodation/accommodation_map_list.js
  static/img/default_room.png
  templates/accommodation/accommodation_create.html
  templates/accommodation/accommodation_location.html
Labels: 🔧 refactor

#82 [feat] mypage 여행 일정 crud 구현 및 accompany와 연결
  accompany/urls.py
  accompany/views.py
  static/mypage/userDetail.css
  templates/accompany/accompany_form.html
  templates/accompany/accompany_list.html
  templates/mypage/myTrip.html
  templates/mypage/plan_detail.html
  templates/mypage/userDetail.html
  users/urls.py
  users/views.py
Labels: 💡 feat

#83 [fix] user_detail 더보기 버튼
  templates/mypage/userDetail.html
Labels: 🛠️ fix

#84 [refactor] 한개의 숙소 후기는 하나의 리스트, 별점 평균 계산, 총 리뷰 수 계산
  accommodation/admin.py
  accommodation/views.py
  templates/accommodation/accommodation_reviewdetail.html
Labels: bug, 🔧 refactor

#88 [fix] 충돌로 인한 mypage 숙소 리뷰 이력 렌더링 재커밋 (#49)
  templates/mypage/userDetail.html
Labels: 🛠️ fix

#89 [refactor] 숙소 후기와 숙소 리뷰를 구별하기 위한 리팩토링 시행
  accommodation/migrations/0003_accommodationreview_is_parent.py
  accommodation/models.py
  accommodation/views.py
  templates/mypage/userDetail.html
  users/views.py
Labels: 🔧 refactor, 🛠️ fix

#90 [feat] mypage planlist, zzim
  static/mypage/userDetail.css
  templates/mypage/editProfile.html
  templates/mypage/myPage.html
  templates/mypage/myTrip.html
  templates/mypage/plan_detail.html
  templates/mypage/planlist.html
  templates/mypage/userDetail.html
  templates/mypage/zzim_list.html
  users/urls.py
  users/views.py
Labels: 💡 feat

#92 [Feat] location 페이지와 filter 페이지 기능 이동 및 location 페이지에 검색 기능 추가 구현
  accommodation/urls.py
  accommodation/views.py
  static/accommodation/accommodation_filter.css
  templates/accommodation/accommodation_filter.html
  templates/accommodation/accommodation_location.html
Labels: 🔧 refactor, 💡 feat

#93 [refactor] accomodation_location.html 일부 수정
  accommodation/migrations/0004_accommodationreview_latitude_and_more.py
  accommodation/models.py
  accommodation/views.py
  config/settings.py
  requirements.txt
  static/accommodation/accommodation_create_map.js
  static/accommodation/accommodation_filter.css
  templates/accommodation/accommodation_location.html
Labels: 🔧 refactor

#98 [refactor] 장기동행, 숙소후기 유저 프로필 연결
  accommodation/views.py
  static/accommodation/accommodation_reviewdetail.css
  templates/accommodation/accommodation_reviewdetail.html
  templates/accompany/accompany_detail.html
Labels: 🔧 refactor

#103 [refactor] 리팩토링
  accompany/filters.py
  accompany/models.py
  accompany/views.py
  config/asgi.py
  static/accommodation/accommodation_filter.css
  static/accommodation/accommodation_location.css
  static/flash/flash_detail.css
  static/flash/flash_list.css
  static/flash/flash_map.js
  static/flash/flash_map_list.js
  templates/accommodation/accommodation_filter.html
  templates/accompany/accompany_detail.html
  templates/flash/flash_detail.html
  templates/flash/flash_list.html
  templates/mypage/myTrip.html
  templates/mypage/plan_detail.html
  templates/mypage/planlist.html
  templates/mypage/userDetail.html
  templates/mypage/zzim_list.html
  users/views.py
Labels: 🔧 refactor

#111 [refactor] 채팅을 위한 asgi.py 수정
  config/asgi.py
Labels: 🔧 refactor

#113 [fix] 배포를 위한 static 설정 변경
  config/settings.py
Labels: 🛠️ fix

#114 [feat] S3 설정을 위한 settings.py 설정 추가 및 의존성 파일 업데이트
  config/settings.py
  requirements.txt
Labels: 💡 feat, chore

#116 [feat] 여행 기능 구현
  accompany/forms.py
  accompany/migrations/0007_travelgroup_call_schedule.py
  accompany/migrations/0008_travelgroup_this_plan.py
  accompany/migrations/0009_auto_20250210_2310.py
  accompany/models.py
  accompany/urls.py
  accompany/views.py
  static/accompany/accompany_create.css
  static/accompany/accompany_list.css
  static/accompany/accompany_map.js
  static/mypage/cms-mypage.css
  static/mypage/userDetail.css
  templates/accompany/accompany_detail.html
  templates/accompany/accompany_form.html
  templates/accompany/accompany_list.html
  templates/mypage/myTrip.html
  templates/mypage/plan_detail.html
  templates/mypage/planlist.html
  templates/mypage/schedule_detail.html
  users/views.py
Labels: 🔧 refactor, 💡 feat

#117 [chore] 배포 서버를 위한 의존성 패키지 버전 변경
  requirements.txt
Labels: chore

#122 [refactor] accompany 이슈 맞춰서 리팩토링
  static/accompany/accompany_create.css
  static/accompany/accompany_detail.css
  static/accompany/accompany_list.css
  templates/accompany/accompany_detail.html
  templates/accompany/accompany_form.html
  templates/accompany/accompany_list.html
Labels: 🔧 refactor

#123 [refactor] accompany refactor
  accompany/migrations/0010_auto_20250212_0436.py
  accompany/models.py
  static/accompany/accompany_create.css
  static/accompany/add_member_toggle.js
  templates/accompany/accompany_detail.html
  templates/accompany/accompany_form.html
  templates/accompany/accompany_list.html
Labels: 🔧 refactor

#124 [chore] 의존성 패키지 업데이트
  requirements.txt
Labels: chore

#126 [feat] 헤더 푸터 (base) 반응형 추가 (#105)
  static/base_css/base.css
  static/img/menu-line.svg
  templates/base/base.html
Labels: 🎨 design, 💡 feat

#128 [design] 메인 페이지 반응형 추가
  static/main/main.css
Labels: 🎨 design

#129 [design] 마이페이지 (mypage.css) 반응형 추가
  static/mypage/myPage.css
Labels: 🎨 design

#132 [feat] 장기동행 리스트 페이지 반응형 구현 및 620px 밑에서는 필터 숨김 처리
  static/accompany/accompany_list.css
  templates/accompany/accompany_list.html
Labels: 🎨 design, 💡 feat

#138 [design] 유저 여행 일정 생성 (userDetail.css) 반응형 추가 (#105)
  static/mypage/userDetail.css
Labels: 🎨 design

#139 [design] 숙소 후기 페이지, 나눔마켓 리스트 페이지 반응형 구현
  static/accommodation/accommodation_filter.css
  static/accommodation/accommodation_location.css
  static/market/market_list.css
  templates/market/market_list.html
Labels: 🎨 design, 💡 feat

#140 [design] 나눔마켓 물품등록 (market_create) 반응형 구현 완료 (#105)
  static/market/market_create.css
Labels: 🎨 design

#144 [design] 숙소 후기 필터링 페이지 반응형, 장기모집 페이지 반응형 추가
  static/accommodation/accommodation_location.css
  static/accompany/accompany_create.css
  static/accompany/accompany_map.css
Labels: 🎨 design

#145 [design] 숙소 후기 후기등록 페이지 반응형 완료 (#105)
  static/accommodation/accommodation_create.css
Labels: 🎨 design

#148 [design] accompany_create 반응형 (#105)
  static/accompany/accompany_create.css
Labels: 🎨 design

#149 [chore] 배포를 위한 settings.py 정적 파일 경로 수정 (#118)
  config/settings.py
Labels: chore

#152 [fix] migrations 충돌 해결
  accommodation/migrations/0003_auto_20250213_1732.py
Labels: 🛠️ fix

#155 [test] 웹소켓 배포 서버 테스트
  config/settings.py
Labels: chore

#156 [chore] settings.py 로컬 환경 복구
  config/settings.py
Labels: chore

#159 [fix] 프로필 이미지 등록 안했을때 default-profile 이미지 안나오는 오류 수정
  config/settings.py
  templates/mypage/userDetail.html
  users/migrations/0002_auto_20250215_2209.py
Labels: 🛠️ fix

#161 [fix] google maps 지도 오류 수정 및 my_trip 함수 context 추가 (#105)
  templates/flash/flash_list.html
  users/views.py
Labels: 🔧 refactor, 🛠️ fix

#162 [fix] 번개모임 검색 필터링 오류 해결 (#105)
  flash/views.py
Labels: 🛠️ fix

#163 [fix] 나눔마켓 user_detail 링크 추가 및 온도 default 36.5로 수정 (#105)
  templates/market/market_detail.html
  users/models.py
Labels: 🔧 refactor

#164 [feat] migrations 파일 추가 (#105)
  users/migrations/0003_alter_user_trust_score.py
Labels: 💡 feat

#174 [refactor] settings.py, asgi.py 배포 환경 구축 및 동일화
  config/asgi.py
  config/settings.py
Labels: 🔧 refactor, chore
