Repository pirogramming/Urabi, pull requests merged in 2025-01, with the labels that each got.

#11 [feat] accompany_list.html 구현
  accompany/urls.py
  accompany/views.py
  static/accompany/accompany_list.css
  static/base_css/base.css
  static/img/accompany_banner.png
  static/register/register.css
  templates/accompany/accompany_list.html
  templates/base/base.html
  templates/register/register.html
  users/urls.py
Labels: 💡 feat

#16 [feat] 숙소 필터링 페이지 템플릿 구현 및 css
  accommodation/__init__.py
  accommodation/admin.py
  accommodation/apps.py
  accommodation/migrations/__init__.py
  accommodation/models.py
  accommodation/tests.py
  accommodation/urls.py
  accommodation/views.py
  config/settings.py
  config/urls.py
  static/accommodation/accommodation_filter.css
  static/img/Map_ex.png
  static/img/empty_star.png
  static/img/fill_star.png
  static/img/heart.svg
  static/img/location.svg
  static/img/room_ex1.png
  static/img/room_ex2.png
  static/img/search-icon.svg
  templates/accommodation/accommodation_filter.html
Labels: 🎨 design, 💡 feat

#26 [feat] 위치 기반 숙소 리스트 페이지 템플릿 및 css 구현
  accommodation/urls.py
  accommodation/views.py
  static/accommodation/accommodation_location.css
  static/img/hotel_test.jpg
  static/img/map_test.png
  static/img/redstar.svg
  templates/accommodation/accommodation_location.html
Labels: 🎨 design, 💡 feat

#27 [Feat] accompany detail, create 템플릿 구현 및 일부 css 수정
  accompany/urls.py
  accompany/views.py
  config/urls.py
  static/accompany/accompany_create.css
  static/accompany/accompany_detail.css
  static/accompany/accompany_list.css
  static/login/login.css
  static/register/register.css
  templates/accompany/accompany_create.html
  templates/accompany/accompany_detail.html
  templates/base/base.html
  users/urls.py
Labels: 🎨 design, 💡 feat

#29 [chore] 데이터베이스 MySQL로 변경 및 연동 완료
  config/settings.py
  data.json
Labels: chore
